#include "tmx_expansion_board.h"

/*
 * Define TMX_EXAMPLE_WITH_TI_DRIVERLIB inside a real MSPM0 SysConfig project
 * after ti_msp_dl_config.h exists. This file is an adapter sketch, not a
 * generated SysConfig replacement.
 */
#if defined(TMX_EXAMPLE_WITH_TI_DRIVERLIB)

#include "ti_msp_dl_config.h"

static void write_gpio(GPIO_Regs *port, uint32_t pin, uint8_t level)
{
    if (level != 0u) {
        DL_GPIO_setPins(port, pin);
    } else {
        DL_GPIO_clearPins(port, pin);
    }
}

static void TmxSyscfg_WriteSignal(tmx_signal_id_t signal, uint8_t level, void *user)
{
    (void)user;

    switch (signal) {
    case TMX_SIG_MOTOR_A_IN1:
        write_gpio(GPIOB, DL_GPIO_PIN_17, level);
        break;
    case TMX_SIG_MOTOR_A_IN2:
        write_gpio(GPIOB, DL_GPIO_PIN_19, level);
        break;
    case TMX_SIG_MOTOR_B_IN1:
        write_gpio(GPIOA, DL_GPIO_PIN_16, level);
        break;
    case TMX_SIG_MOTOR_B_IN2:
        write_gpio(GPIOB, DL_GPIO_PIN_24, level);
        break;
    case TMX_SIG_BUZZER:
        write_gpio(GPIOA, DL_GPIO_PIN_7, level);
        break;
    case TMX_SIG_RGB_PB22:
        write_gpio(GPIOB, DL_GPIO_PIN_22, level);
        break;
    case TMX_SIG_RGB_PB5:
        write_gpio(GPIOB, DL_GPIO_PIN_5, level);
        break;
    case TMX_SIG_RGB_PA18:
        write_gpio(GPIOA, DL_GPIO_PIN_18, level);
        break;
    default:
        break;
    }
}

static void TmxSyscfg_WritePwm(tmx_signal_id_t signal, uint16_t duty_permille, void *user)
{
    (void)user;

    /*
     * Replace these TODO calls with the timer instances generated by SysConfig:
     *   TMX_SIG_MOTOR_A_PWM -> TIMG0_C0_PA12
     *   TMX_SIG_MOTOR_B_PWM -> TIMG0_C1_PA13
     */
    (void)signal;
    (void)duty_permille;
}

static void TmxSyscfg_WriteServo(tmx_signal_id_t signal, uint16_t pulse_us, void *user)
{
    (void)user;

    /*
     * Replace with TIMA0 compare updates:
     *   servo1 PA22/C1, servo2 PA15/C2, servo3 PA17/C3, servo4 PA21/C0.
     * pulse_us == 0 should disable output or write a harmless compare value.
     */
    (void)signal;
    (void)pulse_us;
}

static uint8_t TmxSyscfg_I2cProbe(uint8_t bus_index, uint8_t address_7bit, void *user)
{
    (void)bus_index;
    (void)address_7bit;
    (void)user;

    /*
     * Add a one-byte I2C write/read transaction against I2C0_PA31/PA28.
     * Return 1 only if the device ACKs.
     */
    return 0u;
}

static void TmxSyscfg_UartWrite(uint8_t uart_index,
                                const uint8_t *data,
                                uint16_t len,
                                void *user)
{
    (void)uart_index;
    (void)data;
    (void)len;
    (void)user;

    /*
     * Map uart_index 0..3 to UART0/1/2/3 generated by SysConfig and transmit
     * bytes with timeout. Keep this blocking for smoke tests.
     */
}

static void TmxSyscfg_DelayMs(uint16_t delay_ms, void *user)
{
    (void)user;
    delay_cycles((uint32_t)delay_ms * 32000u);
}

tmx_board_ops_t Board_BuildTmxOps(void)
{
    tmx_board_ops_t ops = {
        .write_signal = TmxSyscfg_WriteSignal,
        .read_signal = 0,
        .write_pwm = TmxSyscfg_WritePwm,
        .write_servo_pulse = TmxSyscfg_WriteServo,
        .i2c_probe = TmxSyscfg_I2cProbe,
        .uart_write = TmxSyscfg_UartWrite,
        .delay_ms = TmxSyscfg_DelayMs,
        .user = 0,
    };

    return ops;
}

#else

void TmxSyscfgAdapterExample_RequiresTiDriverlib(void)
{
}

#endif
