#!/usr/bin/env python3
"""Freeze a validated line-trace tuning plan into a reusable profile."""

from __future__ import annotations

import argparse
import json
import sys
import zlib
from pathlib import Path
from typing import Any


PROFILE_VERSION = 1
PROFILE_CLASSES = {"dry-run-candidate", "bench-candidate", "last-known-good"}


def load_plan(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    if not isinstance(data, dict):
        raise SystemExit(f"plan JSON must be an object: {path}")
    return data


def require_applied_plan(plan: dict[str, Any],
                         profile_class: str,
                         allow_dry_run_source: bool) -> None:
    case = plan.get("case", "unknown")
    validation = plan.get("validation", {})
    if plan.get("expect") != "applied":
        raise SystemExit(f"{case}: only applied tuning plans can be frozen")
    if validation.get("status") != "pass":
        raise SystemExit(f"{case}: validation status is not pass")
    if plan.get("expectation_ok") is not True:
        raise SystemExit(f"{case}: expectation_ok is not true")
    if "candidate" not in plan or "algorithm" not in plan["candidate"]:
        raise SystemExit(f"{case}: missing candidate.algorithm")
    if "sensor" not in plan["candidate"]:
        raise SystemExit(f"{case}: missing candidate.sensor")

    has_hardware = bool(plan.get("hardware_evidence"))
    if profile_class == "last-known-good" and not has_hardware:
        raise SystemExit("last-known-good requires real hardware_evidence=true")
    if not allow_dry_run_source and not has_hardware:
        raise SystemExit("dry-run source needs --allow-dry-run-source")


def stable_crc32(payload: dict[str, Any]) -> int:
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return zlib.crc32(encoded) & 0xFFFFFFFF


def c_array_i16(values: list[int]) -> str:
    return "{ " + ", ".join(str(int(value)) for value in values) + " }"


def c_array_u8(values: list[int]) -> str:
    return "{ " + ", ".join(f"{int(value)}u" for value in values) + " }"


def c_array_u16(values: list[int]) -> str:
    return "{ " + ", ".join(f"{int(value)}u" for value in values) + " }"


def write_header(path: Path, profile: dict[str, Any]) -> None:
    algorithm = profile["algorithm"]
    sensor = profile["sensor"]
    guard = "LINE_TRACE_PROFILE_GENERATED_H"
    lines = [
        "#ifndef " + guard,
        "#define " + guard,
        "",
        "#include \"line_trace_template.h\"",
        "",
        "/* Generated by tools/line_trace_profile_freeze.py. Review before use. */",
        f"#define LINE_TRACE_PROFILE_VERSION {PROFILE_VERSION}u",
        f"#define LINE_TRACE_PROFILE_CRC32 0x{profile['crc32']:08x}u",
        f"#define LINE_TRACE_PROFILE_CLASS \"{profile['profile_class']}\"",
        f"#define LINE_TRACE_PROFILE_SOURCE_CASE \"{profile['source']['case']}\"",
        "",
        "static const line_trace_algorithm_params_t kLineTraceProfileAlgorithm = {",
        f"    .weights = {c_array_i16(algorithm['weights'])},",
        f"    .kp = {int(algorithm['kp'])},",
        f"    .kd = {int(algorithm['kd'])},",
        f"    .base_speed = {int(algorithm['base_speed'])},",
        f"    .max_correction = {int(algorithm['max_correction'])},",
        f"    .corner_slow_error = {int(algorithm['corner_slow_error'])},",
        f"    .min_speed_percent = {int(algorithm['min_speed_percent'])},",
        f"    .search_speed = {int(algorithm['search_speed'])},",
        f"    .ramp_step = {int(algorithm['ramp_step'])},",
        "};",
        "",
        "static const line_trace_sensor_params_t kLineTraceProfileSensor = {",
        f"    .channel_count = {int(sensor['channel_count'])}u,",
        f"    .active_level = (line_trace_active_level_t){int(sensor['active_level'])},",
        f"    .channel_order = {c_array_u8(sensor['channel_order'])},",
        f"    .threshold = {c_array_u16(sensor['threshold'])},",
        f"    .threshold_mode = (line_trace_threshold_mode_t){int(sensor['threshold_mode'])},",
        f"    .i2c_addr = {int(sensor['i2c_addr'])}u,",
        f"    .sensor_enable_mask = {int(sensor['sensor_enable_mask'])}u,",
        "};",
        "",
        "#endif",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def build_profile(plan_path: Path,
                  plan: dict[str, Any],
                  profile_class: str,
                  name: str,
                  note: str) -> dict[str, Any]:
    candidate = plan["candidate"]
    payload = {
        "profile_version": PROFILE_VERSION,
        "profile_class": profile_class,
        "name": name,
        "algorithm": candidate["algorithm"],
        "sensor": candidate["sensor"],
        "source": {
            "plan_path": str(plan_path),
            "case": plan.get("case", ""),
            "seq": candidate.get("seq", 0),
            "mode": plan.get("mode", ""),
            "hardware_evidence": bool(plan.get("hardware_evidence")),
            "elf": plan.get("elf", ""),
            "symbols": plan.get("symbols", {}),
        },
        "verification": {
            "plan_expect": plan.get("expect", ""),
            "plan_validation_status": plan.get("validation", {}).get("status", ""),
            "plan_error_code": plan.get("validation", {}).get("error_code", ""),
            "required_before_flash_commit": [
                "E-003 real bench mapping pass",
                "E-004 low-speed 3 laps or 3 minutes pass",
                "E-005 real hot tuning readback pass",
            ],
        },
        "note": note,
    }
    payload["crc32"] = stable_crc32(payload)
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plan", type=Path, required=True, help="line_trace_swd_tune_plan JSON")
    parser.add_argument("--out-json", type=Path, required=True, help="profile JSON output")
    parser.add_argument("--out-header", type=Path, default=None, help="optional C header output")
    parser.add_argument("--name", default="", help="human readable profile name")
    parser.add_argument("--note", default="", help="short profile note")
    parser.add_argument(
        "--profile-class",
        choices=sorted(PROFILE_CLASSES),
        default="dry-run-candidate",
        help="dry-run candidate is not a last-known-good profile",
    )
    parser.add_argument(
        "--allow-dry-run-source",
        action="store_true",
        help="allow freezing a dry-run plan as a non-LKG candidate profile",
    )
    args = parser.parse_args()

    plan = load_plan(args.plan)
    require_applied_plan(plan, args.profile_class, args.allow_dry_run_source)
    if args.profile_class == "last-known-good" and args.allow_dry_run_source:
        raise SystemExit("last-known-good cannot use --allow-dry-run-source")

    name = args.name or str(plan.get("case", "line_trace_profile"))
    profile = build_profile(args.plan, plan, args.profile_class, name, args.note)

    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(profile, indent=2, ensure_ascii=False), encoding="utf-8")
    if args.out_header is not None:
        write_header(args.out_header, profile)

    print(json.dumps({
        "status": "pass",
        "profile_class": profile["profile_class"],
        "name": profile["name"],
        "crc32": f"0x{profile['crc32']:08x}",
        "out_json": str(args.out_json),
        "out_header": str(args.out_header) if args.out_header else "",
        "hardware_evidence": profile["source"]["hardware_evidence"],
    }, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
