#ifndef TI_MSP_DL_CONFIG_H
#define TI_MSP_DL_CONFIG_H

#define CONFIG_LP_MSPM0G3507
#define CONFIG_MSPM0G3507

#if defined(__ti_version__) || defined(__TI_COMPILER_VERSION__)
#define SYSCONFIG_WEAK __attribute__((weak))
#elif defined(__IAR_SYSTEMS_ICC__)
#define SYSCONFIG_WEAK __weak
#elif defined(__GNUC__)
#define SYSCONFIG_WEAK __attribute__((weak))
#endif

#include <stdbool.h>
#include <ti/devices/msp/msp.h>
#include <ti/driverlib/driverlib.h>
#include <ti/driverlib/m0p/dl_core.h>

#ifdef __cplusplus
extern "C" {
#endif

#define POWER_STARTUP_DELAY (16u)
#define CPUCLK_FREQ (32000000u)

#define PWM_0_INST TIMG0
#define PWM_0_INST_IRQHandler TIMG0_IRQHandler
#define PWM_0_INST_INT_IRQN TIMG0_INT_IRQn
#define PWM_0_PERIOD_TICKS (3200u)
#define GPIO_PWM_0_C0_PORT GPIOA
#define GPIO_PWM_0_C0_PIN DL_GPIO_PIN_12
#define GPIO_PWM_0_C0_IOMUX IOMUX_PINCM34
#define GPIO_PWM_0_C0_IOMUX_FUNC IOMUX_PINCM34_PF_TIMG0_CCP0
#define GPIO_PWM_0_C0_IDX DL_TIMER_CC_0_INDEX
#define GPIO_PWM_0_C1_PORT GPIOA
#define GPIO_PWM_0_C1_PIN DL_GPIO_PIN_13
#define GPIO_PWM_0_C1_IOMUX IOMUX_PINCM35
#define GPIO_PWM_0_C1_IOMUX_FUNC IOMUX_PINCM35_PF_TIMG0_CCP1
#define GPIO_PWM_0_C1_IDX DL_TIMER_CC_1_INDEX

#define UART_0_INST UART0
#define UART_0_INST_FREQUENCY CPUCLK_FREQ
#define UART_0_INST_IRQHandler UART0_IRQHandler
#define UART_0_INST_INT_IRQN UART0_INT_IRQn
#define GPIO_UART_0_RX_PORT GPIOA
#define GPIO_UART_0_TX_PORT GPIOA
#define GPIO_UART_0_RX_PIN DL_GPIO_PIN_1
#define GPIO_UART_0_TX_PIN DL_GPIO_PIN_0
#define GPIO_UART_0_IOMUX_RX IOMUX_PINCM2
#define GPIO_UART_0_IOMUX_TX IOMUX_PINCM1
#define GPIO_UART_0_IOMUX_RX_FUNC IOMUX_PINCM2_PF_UART0_RX
#define GPIO_UART_0_IOMUX_TX_FUNC IOMUX_PINCM1_PF_UART0_TX
#define UART_0_IBRD_32_MHZ_115200_BAUD (17u)
#define UART_0_FBRD_32_MHZ_115200_BAUD (23u)

#define TFT_LCD_WIDTH (128u)
#define TFT_LCD_HEIGHT (160u)
#define TFT_LCD_X_OFFSET (0u)
#define TFT_LCD_Y_OFFSET (0u)
#define TFT_LCD_SCL_PORT GPIOA
#define TFT_LCD_SCL_PIN DL_GPIO_PIN_31
#define TFT_LCD_SCL_IOMUX IOMUX_PINCM6
#define TFT_LCD_SDA_PORT GPIOA
#define TFT_LCD_SDA_PIN DL_GPIO_PIN_28
#define TFT_LCD_SDA_IOMUX IOMUX_PINCM3
#define TFT_LCD_RES_PORT GPIOA
#define TFT_LCD_RES_PIN DL_GPIO_PIN_30
#define TFT_LCD_RES_IOMUX IOMUX_PINCM5
#define TFT_LCD_DC_PORT GPIOB
#define TFT_LCD_DC_PIN DL_GPIO_PIN_15
#define TFT_LCD_DC_IOMUX IOMUX_PINCM32
#define TFT_LCD_CS_PORT GPIOA
#define TFT_LCD_CS_PIN DL_GPIO_PIN_10
#define TFT_LCD_CS_IOMUX IOMUX_PINCM21
#define TFT_LCD_BLK_PORT GPIOB
#define TFT_LCD_BLK_PIN DL_GPIO_PIN_16
#define TFT_LCD_BLK_IOMUX IOMUX_PINCM33

#define MOTOR_A_IN1_PORT GPIOB
#define MOTOR_A_IN1_PIN DL_GPIO_PIN_17
#define MOTOR_A_IN1_IOMUX IOMUX_PINCM43
#define MOTOR_A_IN2_PORT GPIOB
#define MOTOR_A_IN2_PIN DL_GPIO_PIN_19
#define MOTOR_A_IN2_IOMUX IOMUX_PINCM45
#define MOTOR_B_IN1_PORT GPIOA
#define MOTOR_B_IN1_PIN DL_GPIO_PIN_16
#define MOTOR_B_IN1_IOMUX IOMUX_PINCM38
#define MOTOR_B_IN2_PORT GPIOB
#define MOTOR_B_IN2_PIN DL_GPIO_PIN_24
#define MOTOR_B_IN2_IOMUX IOMUX_PINCM52

#define BUZZER_PORT GPIOA
#define BUZZER_PIN DL_GPIO_PIN_7
#define BUZZER_IOMUX IOMUX_PINCM14

#define RGB0_PORT GPIOB
#define RGB0_PIN DL_GPIO_PIN_22
#define RGB0_IOMUX IOMUX_PINCM50
#define RGB1_PORT GPIOB
#define RGB1_PIN DL_GPIO_PIN_5
#define RGB1_IOMUX IOMUX_PINCM18
#define RGB2_PORT GPIOA
#define RGB2_PIN DL_GPIO_PIN_18
#define RGB2_IOMUX IOMUX_PINCM40

#define LINE_TRACE_GPIO_PORT GPIOB
#define LINE_TRACE_CH0_PIN DL_GPIO_PIN_25
#define LINE_TRACE_CH0_IOMUX IOMUX_PINCM56
#define LINE_TRACE_CH1_PIN DL_GPIO_PIN_18
#define LINE_TRACE_CH1_IOMUX IOMUX_PINCM44
#define LINE_TRACE_CH2_PIN DL_GPIO_PIN_21
#define LINE_TRACE_CH2_IOMUX IOMUX_PINCM49
#define LINE_TRACE_CH3_PIN DL_GPIO_PIN_0
#define LINE_TRACE_CH3_IOMUX IOMUX_PINCM12
#define LINE_TRACE_CH4_PIN DL_GPIO_PIN_1
#define LINE_TRACE_CH4_IOMUX IOMUX_PINCM13
#define LINE_TRACE_CH5_PIN DL_GPIO_PIN_10
#define LINE_TRACE_CH5_IOMUX IOMUX_PINCM27
#define LINE_TRACE_CH6_PIN DL_GPIO_PIN_11
#define LINE_TRACE_CH6_IOMUX IOMUX_PINCM28
#define LINE_TRACE_CH7_PIN DL_GPIO_PIN_14
#define LINE_TRACE_CH7_IOMUX IOMUX_PINCM31

#define LINE_MUX_S0_PORT GPIOB
#define LINE_MUX_S0_PIN DL_GPIO_PIN_0
#define LINE_MUX_S0_IOMUX IOMUX_PINCM12
#define LINE_MUX_S1_PORT GPIOB
#define LINE_MUX_S1_PIN DL_GPIO_PIN_1
#define LINE_MUX_S1_IOMUX IOMUX_PINCM13
#define LINE_MUX_S2_PORT GPIOB
#define LINE_MUX_S2_PIN DL_GPIO_PIN_10
#define LINE_MUX_S2_IOMUX IOMUX_PINCM27
#define LINE_MUX_Z_PORT GPIOB
#define LINE_MUX_Z_PIN DL_GPIO_PIN_11
#define LINE_MUX_Z_IOMUX IOMUX_PINCM28
#define LINE_MUX_E_PORT GPIOB
#define LINE_MUX_E_PIN DL_GPIO_PIN_14
#define LINE_MUX_E_IOMUX IOMUX_PINCM31

#define ROTARY_ENC_A_PORT GPIOB
#define ROTARY_ENC_A_PIN DL_GPIO_PIN_25
#define ROTARY_ENC_A_IOMUX IOMUX_PINCM56
#define ROTARY_ENC_C_PORT GPIOB
#define ROTARY_ENC_C_PIN DL_GPIO_PIN_18
#define ROTARY_ENC_C_IOMUX IOMUX_PINCM44
#define ROTARY_ENC_B_PORT GPIOB
#define ROTARY_ENC_B_PIN DL_GPIO_PIN_21
#define ROTARY_ENC_B_IOMUX IOMUX_PINCM49

#define MENU_EXIT_BUTTON_PORT GPIOB
#define MENU_EXIT_BUTTON_PIN DL_GPIO_PIN_12
#define MENU_EXIT_BUTTON_IOMUX IOMUX_PINCM29

#define TMX_SYSCFG_MOTOR_PWM_INST PWM_0_INST
#define TMX_SYSCFG_MOTOR_PWM_PERIOD_TICKS PWM_0_PERIOD_TICKS
#define TMX_SYSCFG_MOTOR_A_PWM_CC_INDEX DL_TIMER_CC_0_INDEX
#define TMX_SYSCFG_MOTOR_B_PWM_CC_INDEX DL_TIMER_CC_1_INDEX
#define TMX_SYSCFG_UART0_INST UART_0_INST
#define TMX_SYSCFG_MOTOR_A_IN1_PORT MOTOR_A_IN1_PORT
#define TMX_SYSCFG_MOTOR_A_IN1_PIN MOTOR_A_IN1_PIN
#define TMX_SYSCFG_MOTOR_A_IN2_PORT MOTOR_A_IN2_PORT
#define TMX_SYSCFG_MOTOR_A_IN2_PIN MOTOR_A_IN2_PIN
#define TMX_SYSCFG_MOTOR_B_IN1_PORT MOTOR_B_IN1_PORT
#define TMX_SYSCFG_MOTOR_B_IN1_PIN MOTOR_B_IN1_PIN
#define TMX_SYSCFG_MOTOR_B_IN2_PORT MOTOR_B_IN2_PORT
#define TMX_SYSCFG_MOTOR_B_IN2_PIN MOTOR_B_IN2_PIN
#define TMX_SYSCFG_BUZZER_PORT BUZZER_PORT
#define TMX_SYSCFG_BUZZER_PIN BUZZER_PIN
#define TMX_SYSCFG_RGB0_PORT RGB0_PORT
#define TMX_SYSCFG_RGB0_PIN RGB0_PIN
#define TMX_SYSCFG_RGB1_PORT RGB1_PORT
#define TMX_SYSCFG_RGB1_PIN RGB1_PIN
#define TMX_SYSCFG_RGB2_PORT RGB2_PORT
#define TMX_SYSCFG_RGB2_PIN RGB2_PIN

void SYSCFG_DL_init(void);
void SYSCFG_DL_initPower(void);
void SYSCFG_DL_GPIO_init(void);
void SYSCFG_DL_SYSCTL_init(void);
void SYSCFG_DL_PWM_0_init(void);
void SYSCFG_DL_UART_0_init(void);

#ifdef __cplusplus
}
#endif

#endif
